version: '2.1'

services:

    mysql:
      container_name: mysql
      image: mysql
      restart: always
      volumes:
        - mysql-db:/var/lib/mysql
#        - "./shared/db:/var/lib/mysql"
      environment:
        - MYSQL_DATABASE=cms
        - MYSQL_USER=root
        - MYSQL_ROOT_PASSWORD=rootpass
      mem_limit: 1g
      env_file: config.env
      networks:
        - xibo_net

    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - MYSQL_USERNAME=root
        - MYSQL_ROOT_PASSWORD=rootpass
      depends_on:
        - mysql
      networks:
        - xibo_net

    xmr:
      container_name: xmr
      image: xibosignage/xibo-xmr:release_1.8.2
      ports:
        - 9505:9505
      restart: always
      mem_limit: 256m
      env_file: config.env
      depends_on:
        - mysql
      networks:
        - xibo_net

    web:
      container_name: web
      image: xibosignage/xibo-cms:release_1.8.2
      volumes:
        - xibo-data:/var/www
#        - "./shared/cms/custom:/var/www/cms/custom"
#        - "./shared/backup:/var/www/backup"
#        - "./shared/cms/web/theme/custom:/var/www/cms/web/theme/custom"
#        - "./shared/cms/library:/var/www/cms/library"
#        - "./shared/cms/web/userscripts:/var/www/cms/web/userscripts"
      restart: always
      links:
        - mysql:mysql
        - xmr:50001
      environment:
        - XMR_HOST=xmr
      env_file: config.env
      ports:
        - 80:80
      mem_limit: 1g
      depends_on:
        - mysql
        - xmr
      networks:
        - xibo_net


volumes:
  mysql-db:
  xibo-data:

networks:
  xibo_net:
    driver: bridge
